version: '3.9'

services:
  server-registry:
    container_name: 'spring-server-registry'
    build:
      dockerfile: './server-registry/Dockerfile'
    ports:
      - "8083:8083"
    healthcheck:
      test: "curl --fail --silent http://localhost:8083/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  api-gateway:
    container_name: 'spring-api-gateway'
    build:
      dockerfile: './api-gateway/Dockerfile'
    ports:
      - "8080:8080"
    depends_on:
      server-registry:
        condition: service_healthy

  crawler-service:
    container_name: 'python-crawler-service'
    build:
      dockerfile: './crawler-service/Dockerfile'
    depends_on:
      server-registry:
        condition: service_healthy
