server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-server-registry:8081/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: document-indexer-module
          uri: lb://document-indexer-service
          predicates:
            - Path=/document-indexer/**
          filters:
            - RewritePath=/document-indexer,/

        - id: crawler-module
          uri: lb://crawler-service
          predicates:
            - Path=/crawler/**
          filters:
            - RewritePath=/crawler,/

        - id: solr-facade-module
          uri: lb://solr-facade-service
          predicates:
            - Path=/facade/**
          filters:
            - RewritePath=/facade,/
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTION
              - HEAD
