solr:
  baseUrl: http://solr-server:8983/solr/briw_core

server:
  port: 8092

spring:
  application:
    name: crawler-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-server-registry:8081/eureka
